# Generated by Django 4.1.5 on 2023-05-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de categoria')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de comuna')),
                ('nombreComuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('idDespacho', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de despacho')),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='Código region')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de rol')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de usuario')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('respuesta', models.CharField(max_length=100)),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pregunta')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de venta')),
                ('nombreVenta', models.CharField(max_length=40)),
                ('fechaVenta', models.DateField()),
                ('total', models.IntegerField()),
                ('fechaDespacho', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('costoDespacho', models.IntegerField()),
                ('carrito', models.IntegerField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de producto')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de direccion')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('codigoPostal', models.IntegerField()),
                ('idComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.comuna')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de detalles')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.CharField(max_length=100)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.venta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.region'),
        ),
    ]
