# Generated by Django 4.2.3 on 2023-07-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_producto_foto_alter_comuna_nombrecomuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
