# Generated by Django 4.2.2 on 2023-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_producto_foto_alter_comuna_nombrecomuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='exit', upload_to='productos'),
            preserve_default=False,
        ),
    ]
